[project]
name = 'lendify'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.collateral-manager]
path = 'contracts/collateral-manager.clar'
clarity_version = 2
epoch = 2.5

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.interest-calculator]
path = 'contracts/interest-calculator.clar'
clarity_version = 2
epoch = 2.5

[contracts.lendify-token]
path = 'contracts/lendify-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.liquidation]
path = 'contracts/liquidation.clar'
clarity_version = 2
epoch = 2.5

[contracts.loan-core]
path = 'contracts/loan-core.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
